### ISSUE TITLE
Undefined array key 0 

### ISSUE THREAD

**Issue by maslme** [bobosch/ods_osm#138] opened 2023-07-13 08:31 UTC
When using the latest git version of ods_osm with TYPO3 11.5.29 under php 8.1.21 i got the following error message:
"PHP Warning: Undefined array key 0 in [...]/typo3cms/typo3_src-11.5.29/typo3/sysext/frontend/Classes/ContentObject/ImageContentObject.php line 89"
[...]
at TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer->cObjGetSingle()
in [...]/typo3cms/verband11/typo3conf/ext/ods_osm/Classes/Controller/PluginController.php line 531
[...]

If I deactivate the ods_osm plugin on this site, the error is gone.

**Comment by albig** [comment] 2023-07-13 18:26
Currently the git master is still equal to version 4.1.2. In line 531 https://github.com/bobosch/ods_osm/blob/v4.1.2/Classes/Controller/PluginController.php#L531 the config array is accessed, which seems to fail in your situation.

Please help me with some details:

1. How did you install the extension? By composer or via download from TER?
2. Did you verify the layer configuration on pid = 0? (The initial base layer data ("Mapnik" etc) should be imported on activation of the extension on pid=0.)
3. Did you include the ods_osm TypoScript template?

Maybe, we get the initial configuration a little more fault tolerant.

**Comment by maslme** [comment] 2023-07-14 08:06
Hey,
thanks for your quickly response. I do my best to answer your questions:

> Please help me with some details:
> 
> 1. How did you install the extension? By composer or via download from TER?
Classic installation via TER / manual upload to typo3conf/ext/
> 2. Did you verify the layer configuration on pid = 0? (The initial base layer data ("Mapnik" etc) should be imported on activation of the extension on pid=0.)
I have several ods_osm layer on pid=0 - so I think that is correct. Also I'm not 100% sure what you mean.
> 3. Did you include the ods_osm TypoScript template?
yes, the TypoScript Setup and Constants are loaded via own sitepackage Extension

**Comment by albig** [comment] 2023-07-14 19:23
> Hey, thanks for your quickly response. I do my best to answer your questions:

Thank you for this. Currently, I have no idea yet.

> > 1. How did you install the extension? By composer or via download from TER?
>    Classic installation via TER / manual upload to typo3conf/ext/

Ok. This should work with 4.1.2, but is not tested by me for longer time. With next release, the classic way will few features in the backend.

> > 2. Did you verify the layer configuration on pid = 0? (The initial base layer data ("Mapnik" etc) should be imported on activation of the extension on pid=0.)
>    I have several ods_osm layer on pid=0 - so I think that is correct. Also I'm not 100% sure what you mean.

That's, what I meant. If you see about 34 "Layer" records, everything is fine.

> > 3. Did you include the ods_osm TypoScript template?
>    yes, the TypoScript Setup and Constants are loaded via own sitepackage Extension

Did you check this with the TypoScript Object Browser (TOB)? Did you write some own TypoScript for ods_osm?

In TOB the default TypoScript Setup of ods_osm should look like this:

![2023-07-14_21-19](https://github.com/bobosch/ods_osm/assets/3354500/8be95e2e-c645-4262-85b2-f5108ba1bf8f)
 
Did you configure the ods_osm plugin or does it just happen with default settings? 
What kind of marker do you want to show? 
Do you use tt_address?

**Comment by albig** [comment] 2023-07-18 20:17
Please use proper quoting in replies here, to make it easier to find your answer. Use the preview tab before posting.

> > Did you configure the ods_osm plugin or does it just happen with default settings?
> I've configured the plugin with pages, sortBy, sortOrder, groupsCombination, includeSubcategories, groups, displayMode, hidePagination and singlePid.

These settings are part of the tt_address list view plugin. Not from ods_osm.

> > Do you use tt_address?
> Yes, I use tt_address and want to show tt_address entries

Maybe, tt_address is sufficiant for your needs. It provides its own map view of address markers.

**Comment by maslme** [comment] 2023-07-20 15:28
Thanks for your hint, now I use tt_address only and it works for me.

**Comment by albig** [comment] 2023-08-04 07:25
Thank you for your feedback. I close this issue because, I cannot reproduce it. If someone else has similar problem, please open a new issue.

**Closed by albig** 2023-08-04 07:25 UTC
